name: 'AWS Deploy Workflow'

on:
  workflow_call:
    inputs:
      cloud:
        required: false
        type: string

permissions:
  contents: read

jobs:
  AWS_build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: AWS Hello
      run: |
        echo "Hello AWS from cloud=${{ inputs.cloud }}"

    - name: Create zip archive for NewsIngestor lambda layer
      run: |
        cd application/NewsIngestor/
        zip -r ../../NewsIngestor_python_dependency_layer.zip ./python -x "*.git*" 

    - name: Upload artifact for NewsIngestor lambda layer
      uses: actions/upload-artifact@v4
      with:
        name: NewsIngestor_python_dependency_layer
        path: NewsIngestor_python_dependency_layer.zip

    - name: Create zip archive for NewsIngestor lambda function
      run: |
        cd application/NewsIngestor
        zip -r ../../NewsIngestor.zip ./* -x "*.git*" "./python/*"

    - name: Upload artifact for NewsIngestor function
      uses: actions/upload-artifact@v4
      with:
        name: NewsIngestor
        path: NewsIngestor.zip

    - name: Create zip archive for CleanerAndNormalizer lambda layer
      run: |
        cd application/CleanerAndNormalizer/
        zip -r ../../CleanerAndNormalizer_python_dependency_layer.zip ./python -x "*.git*" 

    - name: Upload artifact for CleanerAndNormalizer lambda layer
      uses: actions/upload-artifact@v4
      with:
        name: CleanerAndNormalizer_python_dependency_layer
        path: CleanerAndNormalizer_python_dependency_layer.zip

    - name: Create zip archive for CleanerAndNormalizer lambda function
      run: |
        cd application/CleanerAndNormalizer
        zip -r ../../CleanerAndNormalizer.zip ./* -x "*.git*" "./python/*"

    - name: Upload artifact for CleanerAndNormalizer function
      uses: actions/upload-artifact@v4
      with:
        name: CleanerAndNormalizer
        path: CleanerAndNormalizer.zip


  AWS_terraform:
    name: 'Terraform'
    needs: AWS_build
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'production' || 'development' }}
    env:
      DEPLOY_ENV: ${{ github.ref_name == 'master' && 'production' || 'development' }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # configure AWS credentials and region for Terraform to use
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} # ARN of the role to assume. Copy from AWS IAM console and add it in github secrets manually.
        aws-region: ${{ vars.REGION }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.5

    - name: Cache .terraform providers
      uses: actions/cache@v4
      with:
        path: |
          **/.terraform/providers
        key: ${{ runner.os }}-tf-${{ hashFiles('**/.terraform.lock.hcl') }}

    - name: Download Lambda zip artifact for NewsIngestor lambda layer
      uses: actions/download-artifact@v4
      with:
        name: NewsIngestor_python_dependency_layer
        path: aws/infrastructure/NewsIngestor/

    - name: Download Lambda zip artifact for NewsIngestor lambda function
      uses: actions/download-artifact@v4
      with:
        name: NewsIngestor
        path: aws/infrastructure/NewsIngestor/

    - name: Download Lambda zip artifact for CleanerAndNormalizer lambda layer
      uses: actions/download-artifact@v4
      with:
        name: CleanerAndNormalizer_python_dependency_layer
        path: aws/infrastructure/CleanerAndNormalizer/

    - name: Download Lambda zip artifact for CleanerAndNormalizer lambda function
      uses: actions/download-artifact@v4
      with:
        name: CleanerAndNormalizer
        path: aws/infrastructure/CleanerAndNormalizer/

    # Generates an tfvar file for Terraform
    - name: Create terraform.tfvars
      working-directory: ./aws/infrastructure
      run: |
        echo "NEWS_API_KEY = \"${{ secrets.NEWS_API_KEY }}\"" > terraform.tfvars
        echo "COUNTRY= \"${{ vars.COUNTRY }}\"" >> terraform.tfvars
        echo "LANGUAGE= \"${{ vars.LANGUAGE }}\"" >> terraform.tfvars
        echo "RAW_BUCKET= \"${{ vars.RAW_BUCKET }}\"" >> terraform.tfvars
        echo "ENVIRONMENT= \"$DEPLOY_ENV\"" >> terraform.tfvars
        echo "REGION= \"${{ vars.REGION }}\"" >> terraform.tfvars
        echo "RAW_BUCKET_INPUT_KEY= \"${{ vars.RAW_BUCKET_INPUT_KEY }}\"" >> terraform.tfvars
        echo "DB_USER= \"${{ vars.DB_USER }}\"" >> terraform.tfvars
        echo "DB_PASSWORD= \"${{ vars.DB_PASSWORD }}\"" >> terraform.tfvars
        echo "DB_NAME= \"${{ vars.DB_NAME }}\"" >> terraform.tfvars
        cp terraform.tfvars ../infrastructure_tf_state/terraform.tfvars
        cat terraform.tfvars

    # properly format terraform.tfvars file generated above
    - name: Terraform Format terraform.tfvars
      working-directory: ./aws/infrastructure
      run: terraform fmt terraform.tfvars

    - name: replace region name in backend.hcl
      working-directory: ./aws/infrastructure
      run: |
        sed -i "s|__REGION__|${{ vars.REGION }}|g" "backend.hcl"
        sed -i "s|__ENV__|$DEPLOY_ENV|g" "backend.hcl"
        cat backend.hcl
        cp backend.hcl ../infrastructure_tf_state/backend.hcl
        ls ../infrastructure_tf_state/backend.hcl

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      continue-on-error: true
      working-directory: ./aws/infrastructure
      run: terraform init -reconfigure -backend-config=backend.hcl

    - name: Initialize Terraform for bootstrapping state storage resources
      working-directory: ./aws/infrastructure_tf_state
      if: ${{ steps.init.outcome == 'failure' }}
      run: terraform init

    - name: Terraform Plan For Creation of State Storage Resources
      if: ${{ steps.init.outcome == 'failure' }}
      working-directory: ./aws/infrastructure_tf_state
      run: terraform plan -out=tfplan -input=false

    - name: Terraform apply For Creation of State Storage Resources
      if: ${{ steps.init.outcome == 'failure' }}
      working-directory: ./aws/infrastructure_tf_state
      run: terraform plan -out=tfplan -input=false
      
    - name: Terraform apply For Creation of State Storage Resources
      if: ${{ steps.init.outcome == 'failure' }}
      working-directory: ./aws/infrastructure_tf_state
      run: terraform apply -auto-approve -input=false tfplan

    - name: Terraform Init Again
      if: ${{ steps.init.outcome == 'failure' }}
      working-directory: ./aws/infrastructure
      run: terraform init -reconfigure -backend-config=backend.hcl

    # Verify backend is 's3'
    - name: Terraform Backend Info - Verify
      working-directory: ./aws/infrastructure
      run: |
        echo "BACKEND DUMP"
        cat .terraform/terraform.tfstate | sed -n '1,200p' || true
        echo "BACKEND TYPE"
        jq -r '.backend.type' .terraform/terraform.tfstate

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      working-directory: ./aws/infrastructure
      run: terraform fmt -check

    # # validates Terraform
    # - name: Terraform Validate
    #   working-directory: ./aws/infrastructure
    #   run: terraform validate -var-file="terraform.tfvars"
    # Generates an execution plan for Terraform
    - name: Terraform Plan Identity
      working-directory: ./aws/infrastructure
      run: terraform plan -target=module.identity -out=tfplan_identity -input=false -var-file="terraform.tfvars"

    - name: Terraform Apply Identity
      working-directory: ./aws/infrastructure
      run: terraform apply -target=module.identity -auto-approve -input=false tfplan_identity

    - name: Terraform Plan VPC
      working-directory: ./aws/infrastructure
      run: terraform plan -target=module.vpc -out=tfplan_VPC -input=false -var-file="terraform.tfvars"
    - name: Terraform Apply VPC
      working-directory: ./aws/infrastructure
      run: terraform apply -target=module.vpc -auto-approve -input=false tfplan_VPC

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      working-directory: ./aws/infrastructure
      run: terraform plan -out=tfplan -input=false -var-file="terraform.tfvars"

      # On push to "develop", build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      working-directory: ./aws/infrastructure
      # if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      if: github.event_name == 'push'
      run: terraform apply -auto-approve -input=false tfplan
