name: Multi-Cloud CI

on:
  push:
    branches: [ "main" , "develop", "develop_*"]
  pull_request:
permissions:
  id-token: write
  contents: read
jobs:
  aws_deploy:
    if: ${{ vars.CLOUD_PROVIDER == 'AWS' }}
    uses: ./.github/workflows/aws_terraform.yml
    secrets: inherit
    
  gcp_deploy:
    if: ${{ vars.CLOUD_PROVIDER == 'GCP' }}
    uses: ./.github/workflows/gcp_terraform.yml
    secrets: inherit