name: Multi-Cloud CI

on:
  push:
    branches: [ "main" , "develop", "develop_*"]
  pull_request:
permissions:
  id-token: write
  contents: read
jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: |
        echo "Hello cloud=${{ vars.CLOUD_PROVIDER }}" # set it up in settings -> secrets and variables -> action -> project variables

  aws_deploy:
    if: ${{ vars.CLOUD_PROVIDER == 'AWS' }}
    uses: ./.github/workflows/aws_terraform.yml
    secrets: inherit
    
  gcp_deploy:
    if: ${{ vars.CLOUD_PROVIDER == 'GCP' }}
    uses: ./.github/workflows/gcp_terraform.yml
    secrets: inherit