# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: 'Terraform'
# on: { workflow_dispatch: {} }

on:
  push:
    branches: [ "main" , "develop", "develop_*"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # - name: Create zip archive for news_headlines_function lambda function
    #   run: |
    #     cd application/lambda/NewsApi
    #     zip -r ../../../lambda_news_api_fetcher.zip ./* -x "*.git*"

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: lambda_news_api_fetcher
    #     path: lambda_news_api_fetcher.zip

    # - name: Create zip archive for webscraper lambda function
    #   run: |
    #     cd application/lambda/WebPageScraper
    #     zip -r ../../../lambda_web_page_scraper.zip ./* -x "*.git*" "./python/*"

    # - name: Upload artifact for webscraper
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: lambda_web_page_scraper
    #     path: lambda_web_page_scraper.zip

    # - name: Create zip archive for webscraper lambda layer
    #   run: |
    #     cd application/lambda/WebPageScraper
    #     zip -r ../../../webpagescraper_python_dependency_layer.zip ./python -x "*.git*" 

    # - name: Upload artifact for webscraper
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: webpagescraper_python_dependency_layer
    #     path: webpagescraper_python_dependency_layer.zip

  terraform:
    name: 'Terraform'
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'production' || 'development' }}
    env:
      DEPLOY_ENV: ${{ github.ref_name == 'master' && 'production' || 'development' }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # configure AWS credentials and region for Terraform to use
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} # ARN of the role to assume. Copy from AWS IAM console and add it in github secrets manually.
        aws-region: us-east-2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.5

    - name: Cache .terraform providers
      uses: actions/cache@v4
      with:
        path: |
          **/.terraform/providers
        key: ${{ runner.os }}-tf-${{ hashFiles('**/.terraform.lock.hcl') }}

    # - name: Download Lambda zip artifact
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: lambda_news_api_fetcher
    #     path: infrastructure/newsapi_fetcher_lambda/

    # - name: Download Lambda zip artifact for webscraper
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: lambda_web_page_scraper
    #     path: infrastructure/consumer/

    # - name: Download Lambda zip artifact for lambda layer
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: webpagescraper_python_dependency_layer
    #     path: infrastructure/consumer/

    # Generates an tfvar file for Terraform
    - name: Create terraform.tfvars
      working-directory: ./infrastructure
      run: |
        echo "NEWS_API_KEY = \"${{ secrets.NEWS_API_KEY }}\"" > terraform.tfvars
        echo "COUNTRY= \"${{ vars.COUNTRY }}\"" >> terraform.tfvars
        echo "LANGUAGE= \"${{ vars.LANGUAGE }}\"" >> terraform.tfvars
        echo "RAW_BUCKET= \"${{ vars.RAW_BUCKET }}\"" >> terraform.tfvars
        echo "ENVIRONMENT= \"$DEPLOY_ENV\"" >> terraform.tfvars
        cat terraform.tfvars

    # properly format terraform.tfvars file generated above
    - name: Terraform Format terraform.tfvars
      working-directory: ./infrastructure
      run: terraform fmt terraform.tfvars

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      continue-on-error: true
      working-directory: ./infrastructure
      run: terraform init -reconfigure -backend-config=backend.hcl

    - name: Initialize Terraform for bootstrapping state storage resources
      working-directory: ./infrastructure_tf_state
      if: ${{ steps.init.outcome == 'failure' }}
      run: terraform init

    - name: Terraform Plan For Creation of State Storage Resources
      if: ${{ steps.init.outcome == 'failure' }}
      working-directory: ./infrastructure_tf_state
      run: terraform plan -out=tfplan -input=false

    - name: Terraform apply For Creation of State Storage Resources
      if: ${{ steps.init.outcome == 'failure' }}
      working-directory: ./infrastructure_tf_state
      run: terraform plan -out=tfplan -input=false
      
    - name: Terraform apply For Creation of State Storage Resources
      if: ${{ steps.init.outcome == 'failure' }}
      working-directory: ./infrastructure_tf_state
      run: terraform apply -auto-approve -input=false tfplan

    - name: Terraform Init Again
      if: ${{ steps.init.outcome == 'failure' }}
      working-directory: ./infrastructure
      run: terraform init -reconfigure -backend-config=backend.hcl

    # Verify backend is 's3'
    - name: Terraform Backend Info - Verify
      working-directory: infrastructure
      run: |
        echo "BACKEND DUMP"
        cat .terraform/terraform.tfstate | sed -n '1,200p' || true
        echo "BACKEND TYPE"
        jq -r '.backend.type' .terraform/terraform.tfstate

    # - name: Manual State edits
    #   working-directory: infrastructure
    #   run: terraform state pull && terraform state push edited_state_file.json

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      working-directory: ./infrastructure
      run: terraform fmt -check

    # # validates Terraform
    # - name: Terraform Validate
    #   working-directory: ./infrastructure
    #   run: terraform validate -var-file="terraform.tfvars"

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      working-directory: ./infrastructure
      # env:
        # TF_VAR_NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        # TF_VAR_COUNTRY: ${{ vars.COUNTRY }}
        # TF_VAR_LANGUAGE: ${{ vars.LANGUAGE }}
        # TF_VAR_RAW_BUCKET: ${{ vars.RAW_BUCKET }}
        # TF_VAR_ENVIRONMENT: ${{ github.job.environment }}
      run: terraform plan -out=tfplan -input=false -var-file="terraform.tfvars"

      # On push to "develop", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      working-directory: ./infrastructure
      # if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      if: github.event_name == 'push'
      # env:
        # TF_VAR_NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        # TF_VAR_COUNTRY: ${{ vars.COUNTRY }}
        # TF_VAR_LANGUAGE: ${{ vars.LANGUAGE }}
        # TF_VAR_RAW_BUCKET: ${{ vars.RAW_BUCKET }}
        # TF_VAR_ENVIRONMENT: ${{ github.job.environment }}
      run: terraform apply -auto-approve -input=false tfplan
